#use_frameworks!
source 'https://github.com/Cocoapods/Specs.git'
platform :ios, '10.0'

target 'FlatAds_sdk_Example' do
  pod 'FlatAds_sdk', :path => '../'

#  pod "AFNetworking", "4.0.1"
#  pod "FMDB", "2.6.2"
#  pod "MJExtension", "3.2.2"
#  pod "Masonry", "1.1.0"
#  pod "GoogleAds-IMA-iOS-SDK", "~> 3.14.1"
#  pod "YYWebImage", "1.0.5"
#  pod "YYImage/WebP", "1.0.4"
  
  target 'FlatAds_sdk_Tests' do
    inherit! :search_paths

    
  end
end
